apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - certificate.yaml
  - rolebindings.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - httpproxy.yaml
