apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: kube-shell
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 7681
  selector:
    project.app: kube-shell
  type: LoadBalancer